version: "3.7"
services:
  groove-db:
    platform: linux/amd64
    image: 'mysql:8.0'
    container_name: groove_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=groove
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=vogus
      - MYSQL_PASSWORD=vogus!
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d