rootProject.name = "groove"
include("groove-api")
include("groove-security:auth")
include("groove-security:auth-api")
include("groove-security:spring-security")
include("storage")
include("common")
include("redis")
include("mail")
include("object-storage")
include("client:user")