spring:
  config:
    import:
      - mail.yaml
      - object-storage.yaml

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: pass

  sql.init.mode: never

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

authentication:
  auth-key: MjVHxjrKDMe8uTA66pIKmgnzUbmakXItJ0o7Sd5s5gZzfzOE0IeC1CMXT3Z6pkveGErsZFc8LD9qhAEZGZIS9M4gi9h7ru8wNQvCJbq4ByUJTnXOJbEUNEiJ1PDXC5cqBlpBGzmi62JhUmpY74IdQIQt0iWMR6sdOVMUsWmV1AP60Pfv5Tm0TptQpEB42YQaj9N5BfhnaBFekuc3UzfYUxKuPSC7IjVQXL0x1VPt053tIQHCEiLrVSPL3d8RE1m5
  access-expiration: 1h
  refresh-expiration: 10d

---

spring.config.activate.on-profile: dev

# heroku data resource
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql.init.mode: never

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect