name: Groove CD with Gradle

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      issues: read
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for ./gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "groove-server"
          heroku_email: "mr.bogus2023@gmail.com"