name: Groove CD with Gradle

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      issues: read
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "groove-server"
          heroku_email: "mr.bogus2023@gmail.com"