spring:
  redis:
    host: localhost
    port: 6379

---

# heroku data resource
spring.config.activate.on-profile: dev

spring:
  redis:
#    url: ${REDIS_TLS_URL}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}